require("dotenv").config()

const express =require("express")
const cors = require("cors")
const bodyParser = require("body-parser")
const adminrouter=require('./routes/admin.routes')
const catrouter=require('./routes/cat.routes')
const scatrouter=require('./routes/subcat.routes')
const userrouter=require('./routes/user.routes')
const cnrouter=require('./routes/country.routes')
const staterouter=require('./routes/state.routes')
const cityrouter=require('./routes/city.routes')
const productRoutes = require("./routes/product.routes")
const wishlistRoutes = require("./routes/wishlist.routes")

const app=express()
app.use(cors())
app.use(bodyParser.json())
app.use('/api/admin',adminrouter)
app.use('/api/cat',catrouter)
app.use('/api/subcat',scatrouter)
app.use('/api/user',userrouter)
app.use('/api/country',cnrouter)
app.use('/api/state',staterouter)
app.use('/api/city',cityrouter)
app.use("/api/product", productRoutes)
app.use("/api/wishlist", wishlistRoutes)
PORT =process.env.PORT||5000
app.listen(PORT,()=>console.log(`server is running on ${PORT}`))